name: Deploy to GitHub Pages

on:
  # Akan dijalankan setiap kali ada push (merge) ke branch main
  push:
    branches: ["main"]

  # Memungkinkan deploy secara manual dari tab Actions di GitHub
  workflow_dispatch:

# Mengatur permission GitHub Token agar bisa melakukan deploy ke GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Mencegah adanya deployment yang berjalan bentrok secara bersamaan
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job untuk melakukan deployment
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5
        
      - name: Upload Repository Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Mengupload seluruh file di dalam directory ini (termasuk index.html & style.css)
          path: '.'
          
      - name: Deploy ke GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
